import type { Metadata, Viewport } from "next";
import { Space_Grotesk, Inter_Tight, Noto_Sans_Thaana } from "next/font/google";
import "@/styles/globals.css";
// buttons.css carries the generic depth-only bevel for every plain <button>.
// It loads BEFORE the Arena sheets on purpose: its hover rule is
// `button:hover:not(:disabled)`, which outranks a single class, so anything
// that ties with it on specificity has to come later to win.
import "@/styles/buttons.css";
import "@/styles/arena.css";
// Generated from the design boards by scripts/port-board.mjs — the board's
// own CSS, namespaced and recoloured. Do not edit these by hand.
import "@/styles/arena-mindi.css";
import "@/styles/arena-gin-board.css";
import "@/styles/arena-lobby.css";
import "@/styles/arena-result.css";
import "@/styles/arena-phone.css";
// The shared app-screen layer: arena-app.css is generated from
// design/arena/app-reference.css, arena-shell.css is the hand-written half
// (fluid geometry the fixed artboards don't have to describe, and the
// existing shell retinted onto the board).
import "@/styles/arena-app.css";
import "@/styles/arena-shell.css";
// Per-board sheets for the app screens, generated the same way, plus the
// hand-written fluid half that the fixed artboards do not describe.
import "@/styles/arena-home.css";
import "@/styles/arena-profile.css";
import "@/styles/arena-inventory.css";
import "@/styles/arena-shop.css";
import "@/styles/arena-shopvip.css";
import "@/styles/arena-rewards.css";
import "@/styles/arena-friends.css";
import "@/styles/arena-messages.css";
import "@/styles/arena-clubs.css";
import "@/styles/arena-leaderboard.css";
import "@/styles/arena-achievements.css";
import "@/styles/arena-league.css";
import "@/styles/arena-halloffame.css";
import "@/styles/arena-settings.css";
import "@/styles/arena-screens.css";
// The phone. arena-phone.css is the layer the M boards share, generated by
// port-board.mjs --shared; the per-board sheets follow it so a board that
// restyles a shared rule wins. arena-phone-shell.css is the hand-written
// half: fixed chrome, safe areas, and the media queries that decide which
// shell is on screen.
import "@/styles/arena-phone.css";
import "@/styles/arena-mhome.css";
import "@/styles/arena-mmore.css";
import "@/styles/arena-phome.css";
// MPlay is the portrait Play lobby; MPlayFind is MPlay with the rotate sheet
// open, and its stylesheet came out byte-for-byte identical, so one sheet
// serves both states. MRotate is the gate over a table held upright.
import "@/styles/arena-mplay.css";
import "@/styles/arena-mrotate.css";
// The four the phone gets held sideways: the Play lobby, the two tables and
// the hand result, each an 844x390 composition scaled to the visible
// viewport by components/game/ArenaStage.
import "@/styles/arena-plobby.css";
import "@/styles/arena-pmindi.css";
import "@/styles/arena-pgin.css";
import "@/styles/arena-presult.css";
// The portrait screens. MShopBuy and MShopShort came out byte-identical to
// MShop - they are MShop with a sheet open - so one sheet serves all three.
import "@/styles/arena-mprofile.css";
import "@/styles/arena-minventory.css";
import "@/styles/arena-mfriends.css";
import "@/styles/arena-mmessages.css";
import "@/styles/arena-mchat.css";
import "@/styles/arena-mclubs.css";
import "@/styles/arena-mleaderboard.css";
import "@/styles/arena-machievements.css";
import "@/styles/arena-mleague.css";
import "@/styles/arena-mhalloffame.css";
import "@/styles/arena-mshop.css";
import "@/styles/arena-mshopvip.css";
import "@/styles/arena-mrewards.css";
import "@/styles/arena-msettings.css";
import "@/styles/arena-phone-shell.css";
// Owned by the second agent building the Friends/Clubs/Leaderboard/Settings
// screens (design/arena/WORKSPLIT.md). Imported here, empty, so that agent
// never has to edit this file and the two of us can't collide in it.
import "@/styles/arena-social.css";
import "@/styles/arena-compete.css";
import "@/styles/mindi.css";
import "@/styles/gin.css";
import { AuthProvider } from "@/contexts/AuthContext";
import { SettingsProvider } from "@/contexts/SettingsContext";
import { EconomyProvider } from "@/contexts/EconomyContext";
import { ToastProvider } from "@/contexts/ToastContext";
import { MotionProvider } from "@/components/system/MotionProvider";
import { AppShell } from "@/components/layout/AppShell";

/**
 * Arena typefaces (design/arena/README.md "Type").
 *
 * Exposed as CSS variables rather than class names because three families
 * have to coexist: --font-ui is the body default, --font-display drives the
 * tracked uppercase headlines and buttons, and --font-thaana carries Dhivehi
 * (މިންޑި, ޖިން ރަމީ) which the Latin faces cannot render at all.
 */
const display = Space_Grotesk({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-display",
  display: "swap",
});
const ui = Inter_Tight({
  subsets: ["latin"],
  style: ["normal", "italic"],
  variable: "--font-ui",
  display: "swap",
});
const thaana = Noto_Sans_Thaana({
  subsets: ["thaana"],
  weight: ["600", "700"],
  variable: "--font-thaana",
  display: "swap",
});

/**
 * Canonical origin. Used by metadataBase so the relative OG/Twitter image
 * paths below resolve to absolute URLs - social crawlers reject relative
 * ones. Override via NEXT_PUBLIC_SITE_URL when deploying to a custom
 * domain so previews don't keep pointing at the Netlify subdomain.
 */
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://tsbai.netlify.app";

const DESCRIPTION =
  "Play Mindi and Gin Rummy online — ranked matches, private rooms with friends, clubs, and the Weekend League. The premium Maldivian card game experience.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    // Child routes set only their own title; this appends the brand so
    // every tab and search result reads "<Page> — Thaasbai".
    default: "Thaasbai — The Home of Maldivian Card Games",
    template: "%s — Thaasbai",
  },
  description: DESCRIPTION,
  applicationName: "Thaasbai",
  keywords: ["Mindi", "Gin Rummy", "Maldivian card games", "Thaasbai", "online card game", "ranked card game"],
  manifest: "/manifest.json",
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
  openGraph: {
    type: "website",
    siteName: "Thaasbai",
    title: "Thaasbai — The Home of Maldivian Card Games",
    description: DESCRIPTION,
    url: SITE_URL,
    images: [{ url: "/og-image.png", width: 1200, height: 630, alt: "Thaasbai — The Home of Maldivian Card Games" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Thaasbai — The Home of Maldivian Card Games",
    description: DESCRIPTION,
    images: ["/og-image.png"],
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // maximumScale/userScalable were previously pinned to block pinch-zoom
  // for an "app-like" feel. That's a WCAG 1.4.4 failure - it stops anyone
  // who needs to magnify text from doing so, and modern iOS ignores it on
  // form fields anyway. Zoom stays enabled; the layout is responsive
  // enough that it isn't needed for normal use.
  themeColor: "#0F0F0F",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      {/* The three families ride as variables; the body font itself comes
          from Tailwind's `sans`, which now maps to var(--font-ui). */}
      <body className={`${display.variable} ${ui.variable} ${thaana.variable} font-sans`}>
        <MotionProvider><AuthProvider>
          <SettingsProvider>
            <EconomyProvider>
              {/* Innermost so any screen can raise a toast, and so the
                  toast stack renders above the app's own fixed chrome. */}
              <ToastProvider>
                <AppShell>{children}</AppShell>
              </ToastProvider>
            </EconomyProvider>
          </SettingsProvider>
        </AuthProvider></MotionProvider>
      </body>
    </html>
  );
}
