/** Arena Rooms / RoomLobby copy in the four supported languages. */
const words = (en: string, dv: string, hi: string, bn: string) => ({ en, dv, hi, bn });
export const ROOM_STRINGS = {
  room_you: words("You", "ތިބާ", "आप", "আপনি"),
  room_online: words("Online", "އޮންލައިން", "ऑनलाइन", "অনলাইন"),
  room_offline: words("Offline", "އޮފްލައިން", "ऑफ़लाइन", "অফলাইন"),
  room_startMatch: words("Start match", "މެޗް ފަށާ", "मैच शुरू करें", "ম্যাচ শুরু করুন"),
  room_waitingPlayers: words("Waiting for players", "ކުޅުންތެރިންނަށް މަޑުކުރަނީ", "खिलाड़ियों का इंतज़ार", "খেলোয়াড়দের অপেক্ষা"),
  room_on: words("On", "އޮން", "चालू", "চালু"),
  room_off: words("Off", "އޮފް", "बंद", "বন্ধ"),
  room_allFourSeated: words("All four seated", "ހަތަރު މީހުންވެސް އިށީންނައިފި", "चारों बैठ गए", "চারজনই বসেছেন"),
  room_bothSeated: words("Both seated", "ދެމީހުންވެސް އިށީންނައިފި", "दोनों बैठ गए", "দুজনই বসেছেন"),
  room_title: words("Private Room", "ޕްރައިވެޓް ރޫމް", "प्राइवेट रूम", "প্রাইভেট রুম"),
  room_people: words("Play with your people", "ތިބާގެ ރަޙްމަތްތެރިންނާއެކު ކުޅޭ", "अपने लोगों के साथ खेलें", "আপনজনদের সঙ্গে খেলুন"),
  room_intro: words("Open a table for friends, or join theirs with a code.", "ރަޙްމަތްތެރިންނަށް މޭޒެއް ހަދާ، ނުވަތަ ކޯޑަކުން އެބައިމީހުންގެ މޭޒަށް ވަދޭ.", "दोस्तों के लिए मेज़ खोलें या कोड से उनकी मेज़ पर जाएं।", "বন্ধুদের জন্য টেবিল খুলুন বা কোড দিয়ে তাদের টেবিলে যোগ দিন।"),
  room_create: words("Create a room", "ރޫމެއް ހަދާ", "रूम बनाएं", "রুম তৈরি করুন"),
  room_join: words("Join room", "ރޫމަށް ވަދޭ", "रूम में शामिल हों", "রুমে যোগ দিন"),
  room_joinShort: words("Join", "ވަދޭ", "जुड़ें", "যোগ দিন"),
  room_joinTab: words("Join a room", "ރޫމަކަށް ވަދޭ", "रूम में शामिल हों", "একটি রুমে যোগ দিন"),
  room_joinCode: words("Join with a code", "ކޯޑަކުން ވަދޭ", "कोड से शामिल हों", "কোড দিয়ে যোগ দিন"),
  room_pickGame: words("Pick the game, then share your code.", "ގޭމް ހޮވާ، ދެން ކޯޑް ހިއްސާކުރޭ.", "खेल चुनें, फिर अपना कोड साझा करें।", "খেলা বেছে নিন, তারপর কোড শেয়ার করুন।"),
  room_askCode: words("Ask the host for their six-character code.", "ހޮސްޓުގެ ހައެއް އަކުރުގެ ކޯޑް އަހާ.", "मेज़बान से छह अक्षरों का कोड मांगें।", "হোস্টের কাছে ছয় অক্ষরের কোড চান।"),
  room_game: words("Game", "ގޭމް", "खेल", "খেলা"),
  room_seats: words("Seats", "ގޮނޑިތައް", "सीटें", "আসন"),
  room_mindiSeats: words("2 or 4 players", "2 ނުވަތަ 4 ކުޅުންތެރިން", "2 या 4 खिलाड़ी", "২ বা ৪ জন"),
  room_mindiSeatsShort: words("2 or 4 players · teams", "2 ނުވަތަ 4 · ޓީމް", "2 या 4 खिलाड़ी · टीम", "২ বা ৪ জন · দল"),
  room_ginSeats: words("2 players", "2 ކުޅުންތެރިން", "2 खिलाड़ी", "২ জন"),
  room_four: words("4 · Two teams", "4 · ދެ ޓީމް", "4 · दो टीमें", "৪ · দুই দল"),
  room_fourShort: words("4 · Teams", "4 · ޓީމް", "4 · टीम", "৪ · দল"),
  room_two: words("2 · Head to head", "2 · އެކަކާ އެކަކު", "2 · आमने सामने", "২ · মুখোমুখি"),
  room_twoShort: words("2 · One on one", "2 · އެކަކާ އެކަކު", "2 · एक बनाम एक", "২ · এক বনাম এক"),
  room_ginHelp: words("Gin Rummy is always one on one.", "ޖިން ރަމީ އަކީ ހަމަ އެކަކާ އެކަކު ކުޅޭ ގޭމެއް.", "जिन रमी हमेशा एक बनाम एक है।", "জিন রামি সবসময় এক বনাম এক।"),
  room_teamHelp: words("Two teams of two. You play with the player opposite you.", "ދެމީހުންގެ ދެ ޓީމް. ކުޅެވޭނީ ތިބާއާ އިސްކަށީގައި ތިބި މީހާއާއެކު.", "दो खिलाड़ियों की दो टीमें। सामने बैठा खिलाड़ी आपका साथी है।", "দুজনের দুটি দল। বিপরীতে বসা খেলোয়াড় আপনার সঙ্গী।"),
  room_duelHelp: words("One on one. Each player keeps their own tricks.", "އެކަކާ އެކަކު. ކޮންމެ މީހަކު އަމިއްލަ ޓްރިކްތައް ބެލެހެއްޓޭ.", "एक बनाम एक। हर खिलाड़ी अपनी ट्रिक रखता है।", "এক বনাম এক। প্রত্যেকে নিজের ট্রিক রাখে।"),
  room_password: words("Password", "ޕާސްވޯޑް", "पासवर्ड", "পাসওয়ার্ড"),
  room_optional: words("Optional", "އިޚްތިޔާރީ", "वैकल्पिक", "ঐচ্ছিক"),
  room_lock: words("Lock this room", "މި ރޫމް ލޮކްކުރޭ", "इस रूम को लॉक करें", "রুমটি লক করুন"),
  room_protect: words("Protect room with password", "ޕާސްވޯޑަކުން ރޫމް ލޮކްކުރޭ", "रूम को पासवर्ड से सुरक्षित करें", "পাসওয়ার্ড দিয়ে রুম সুরক্ষিত করুন"),
  room_anyoneCode: words("Anyone with the code can join.", "ކޯޑް ހުރި ކޮންމެ މީހަކު ވެސް ވަދެވޭނެ.", "कोड वाला कोई भी शामिल हो सकता है।", "কোড থাকলে যে কেউ যোগ দিতে পারে।"),
  room_passwordOnly: words("Only players with the password can join.", "ވަދެވޭނީ ޕާސްވޯޑް ހުރި ކުޅުންތެރިންނަށް.", "केवल पासवर्ड वाले खिलाड़ी जुड़ सकते हैं।", "শুধু পাসওয়ার্ড থাকা খেলোয়াড়রা যোগ দিতে পারে।"),
  room_enterPassword: words("Enter room password", "ރޫމް ޕާސްވޯޑް ލިޔޭ", "रूम का पासवर्ड डालें", "রুমের পাসওয়ার্ড লিখুন"),
  room_showPassword: words("Show password", "ޕާސްވޯޑް ދައްކާ", "पासवर्ड दिखाएं", "পাসওয়ার্ড দেখান"),
  room_hidePassword: words("Hide password", "ޕާސްވޯޑް ފޮރުވާ", "पासवर्ड छिपाएं", "পাসওয়ার্ড লুকান"),
  room_passwordTitle: words("Room password", "ރޫމް ޕާސްވޯޑް", "रूम का पासवर्ड", "রুমের পাসওয়ার্ড"),
  room_joinPassword: words("Join room password", "ވަންނަން ރޫމް ޕާސްވޯޑް", "रूम में जुड़ने का पासवर्ड", "রুমে যোগ দেওয়ার পাসওয়ার্ড"),
  room_lockedAsk: words("{code} is locked. Ask {host}.", "{code} ލޮކްކޮށްފައި. {host} އާ އަހާ.", "{code} लॉक है। {host} से पूछें।", "{code} লক করা। {host}-কে জিজ্ঞাসা করুন।"),
  room_code: words("Room code", "ރޫމް ކޯޑް", "रूम कोड", "রুম কোড"),
  room_paste: words("Paste code", "ކޯޑް ޕޭސްޓްކުރޭ", "कोड पेस्ट करें", "কোড পেস্ট করুন"),
  room_codeHint: words("Letters A–Z and numbers 2–9", "އަކުރު A–Z އަދި ނަންބަރު 2–9", "अक्षर A–Z और अंक 2–9", "অক্ষর A–Z ও সংখ্যা 2–9"),
  room_codeHintShort: words("A–Z and 2–9", "A–Z އަދި 2–9", "A–Z और 2–9", "A–Z ও 2–9"),
  room_card: words("Room Card", "ރޫމް ކާޑް", "रूम कार्ड", "রুম কার্ড"),
  room_cardActive: words("Room Card active", "ރޫމް ކާޑް އެކްޓިވް", "रूम कार्ड सक्रिय", "রুম কার্ড সক্রিয়"),
  room_noCard: words("No active Room Card", "އެކްޓިވް ރޫމް ކާޑެއް ނެތް", "कोई सक्रिय रूम कार्ड नहीं", "সক্রিয় রুম কার্ড নেই"),
  room_noCardShort: words("No Room Card", "ރޫމް ކާޑެއް ނެތް", "रूम कार्ड नहीं", "রুম কার্ড নেই"),
  room_needsCard: words("Hosting needs one. Joining is always free.", "ހޮސްޓްކުރަން ކާޑެއް ބޭނުން. ވަނުން ހިލޭ.", "मेज़बानी के लिए कार्ड चाहिए। जुड़ना हमेशा मुफ़्त है।", "হোস্ট করতে কার্ড লাগে। যোগ দেওয়া সবসময় বিনামূল্যে।"),
  room_needsCardShort: words("Needed to host. Joining is free.", "ހޮސްޓްކުރަން ބޭނުން. ވަނުން ހިލޭ.", "मेज़बानी के लिए ज़रूरी। जुड़ना मुफ़्त।", "হোস্ট করতে লাগে। যোগ দেওয়া বিনামূল্যে।"),
  room_cardTime: words("{hours}-Hour card · {minutes} min left", "{hours} ގަޑިއިރުގެ ކާޑް · {minutes} މިނެޓް ބާކީ", "{hours} घंटे का कार्ड · {minutes} मिनट बाकी", "{hours} ঘণ্টার কার্ড · {minutes} মিনিট বাকি"),
  room_getCard: words("Get a card", "ކާޑެއް ގަންނާ", "कार्ड लें", "কার্ড নিন"),
  room_getOne: words("Get one", "ގަންނާ", "लें", "নিন"),
  room_manage: words("Manage", "ބެލެހެއްޓޭ", "प्रबंधित करें", "পরিচালনা"),
  room_host: words("Host", "ހޮސްޓް", "मेज़बान", "হোস্ট"),
  room_covered: words("Covered by your Room Card. Create as many rooms as you like.", "ތިބާގެ ރޫމް ކާޑުން ލިބޭ. ކިތަންމެ ރޫމެއް ހަދާ.", "आपके रूम कार्ड में शामिल। जितने चाहें रूम बनाएं।", "আপনার রুম কার্ডে অন্তর্ভুক্ত। যত ইচ্ছা রুম তৈরি করুন।"),
  room_activateCard: words("Activate a Room Card to host. Joining is always free.", "ހޮސްޓްކުރަން ރޫމް ކާޑެއް އެކްޓިވްކުރޭ. ވަނުން ހިލޭ.", "मेज़बानी के लिए रूम कार्ड सक्रिय करें। जुड़ना मुफ़्त है।", "হোস্ট করতে রুম কার্ড সক্রিয় করুন। যোগ দেওয়া বিনামূল্যে।"),
  room_invites: words("Invites", "ދަޢުވަތުތައް", "निमंत्रण", "আমন্ত্রণ"),
  room_invitedYou: words("{name} invited you", "{name} ދަޢުވަތުދީފި", "{name} ने आपको बुलाया", "{name} আপনাকে আমন্ত্রণ জানিয়েছে"),
  room_inviteSeats: words("{n} of {max} seated", "{n} / {max} އިށީންދެފައި", "{max} में से {n} बैठे", "{max}-এর মধ্যে {n} জন বসেছে"),
  room_inviteSeatsShort: words("{n} of {max}", "{n} / {max}", "{max} में से {n}", "{max}-এর মধ্যে {n}"),
  room_minutesAgo: words("{n} min ago", "{n} މިނެޓް ކުރިން", "{n} मिनट पहले", "{n} মিনিট আগে"),
  room_noInvites: words("No incoming invites.", "ދަޢުވަތެއް ނެތް.", "कोई निमंत्रण नहीं।", "কোনো আমন্ত্রণ নেই।"),
  room_inviteLoadError: words("Could not load invitations.", "ދަޢުވަތުތައް ލޯޑްނުވި.", "निमंत्रण लोड नहीं हुए।", "আমন্ত্রণ লোড করা যায়নি।"),
  room_recent: words("Recent rooms", "ފަހުގެ ރޫމްތައް", "हाल के रूम", "সাম্প্রতিক রুম"),
  room_recentHelp: words("Rooms you created or joined on this device.", "މި ޑިވައިސުން ހެދި ނުވަތަ ވަން ރޫމްތައް.", "इस डिवाइस पर बनाए या जुड़े रूम।", "এই ডিভাইসে তৈরি করা বা যোগ দেওয়া রুম।"),
  room_noRecent: words("Rooms you create or join will appear here.", "ހަދާ ނުވަތަ ވަންނަ ރޫމްތައް މިތާ ފެންނާނެ.", "आपके बनाए या जुड़े रूम यहाँ दिखेंगे।", "আপনার তৈরি করা বা যোগ দেওয়া রুম এখানে দেখা যাবে।"),
  room_recentError: words("Could not load {code}.", "{code} ލޯޑްނުވި.", "{code} लोड नहीं हुआ।", "{code} লোড করা যায়নি।"),
  room_viewAll: words("View all", "ހުރިހާ ދައްކާ", "सभी देखें", "সব দেখুন"),
  room_showLess: words("Show less", "ކުޑަކޮށް ދައްކާ", "कम दिखाएं", "কম দেখান"),
  room_gameRoom: words("{game} room", "{game} ރޫމް", "{game} रूम", "{game} রুম"),
  room_phoneSeatCount: words("{n} of {max} · {mode}", "{max} ގެ {n} · {mode}", "{max} में से {n} · {mode}", "{max} এর মধ্যে {n} · {mode}"),
  room_needFourSeats: words("Needs all four seats.", "ހަތަރު ގޮނޑިވެސް ބޭނުން.", "चारों सीटें भरनी होंगी।", "চারটি আসনই পূর্ণ হতে হবে।"),
  room_needTwoSeats: words("Needs both seats.", "ދެ ގޮނޑިވެސް ބޭނުން.", "दोनों सीटें भरनी होंगी।", "দুটি আসনই পূর্ণ হতে হবে।"),
  room_available: words("Available", "ލިބެންހުރި", "उपलब्ध", "উপলব্ধ"),
  room_full: words("Full", "ފުރިފައި", "भरा हुआ", "পূর্ণ"),
  room_started: words("Game started", "ގޭމް ފެށިފައި", "खेल शुरू", "খেলা শুরু হয়েছে"),
  room_startedShort: words("Started", "ފެށިފައި", "शुरू", "শুরু"),
  room_closed: words("Closed", "ބަންދު", "बंद", "বন্ধ"),
  room_expired: words("Expired", "މުއްދަތު ހަމަވެފައި", "समाप्त", "মেয়াদ শেষ"),
  room_unavailable: words("Unavailable", "ނުލިބޭ", "अनुपलब्ध", "অনুপলব্ধ"),
  room_tableFull: words("Table full", "މޭޒު ފުރިފައި", "मेज़ भरी हुई", "টেবিল পূর্ণ"),
  room_creating: words("Creating room…", "ރޫމް ހަދަނީ…", "रूम बन रहा है…", "রুম তৈরি হচ্ছে…"),
  room_joining: words("Joining…", "ވަންނަނީ…", "जुड़ रहे हैं…", "যোগ দিচ্ছে…"),
  room_created: words("Room created", "ރޫމް ހެދިއްޖެ", "रूम बन गया", "রুম তৈরি হয়েছে"),
  room_joined: words("Joined room", "ރޫމަށް ވަންއިއްޖެ", "रूम में जुड़ गए", "রুমে যোগ দিয়েছেন"),
  room_clipboardUnavailable: words("Clipboard unavailable. Paste your code into the field.", "ކްލިޕްބޯޑް ނުލިބޭ. ކޯޑް ފީލްޑަށް ޕޭސްޓްކުރޭ.", "क्लिपबोर्ड उपलब्ध नहीं। कोड फ़ील्ड में पेस्ट करें।", "ক্লিপবোর্ড পাওয়া যাচ্ছে না। ঘরে কোড পেস্ট করুন।"),
  room_swapPartners: words("Swap partners", "ޕާޓްނަރުން ބަދަލުކުރޭ", "साथी बदलें", "সঙ্গী বদলান"),
  room_waitMore: words("Waiting for {n} more", "އިތުރު {n} މީހުންނަށް މަޑުކުރަނީ", "{n} और खिलाड़ियों का इंतज़ार", "আরও {n} জনের অপেক্ষা"),
  room_moreToGo: words("{n} more to go", "އިތުރު {n} މީހުން", "{n} और चाहिए", "আরও {n} জন চাই"),
  room_startReady: words("Start when you are ready.", "ތައްޔާރުވުމުން ފަށާ.", "तैयार हों तो शुरू करें।", "প্রস্তুত হলে শুরু করুন।"),
  room_startReadyShort: words("Start when ready", "ތައްޔާރުވުމުން ފަށާ", "तैयार हों तो शुरू करें", "প্রস্তুত হলে শুরু করুন"),
  room_waitHost: words("Waiting for {host} to start", "{host} ފަށަން މަޑުކުރަނީ", "{host} के शुरू करने का इंतज़ार", "{host}-এর শুরু করার অপেক্ষা"),
  room_openSeat: words("Open seat", "ހުސް ގޮނޑި", "खाली सीट", "খালি আসন"),
  room_inviteFriend: words("Invite a friend", "ރަޙްމަތްތެރިއަކަށް ދަޢުވަތުދޭ", "दोस्त को बुलाएं", "বন্ধুকে আমন্ত্রণ জানান"),
  room_inviteFriends: words("Invite friends", "ރަޙްމަތްތެރިންނަށް ދަޢުވަތުދޭ", "दोस्तों को बुलाएं", "বন্ধুদের আমন্ত্রণ জানান"),
  room_remove: words("Remove from room", "ރޫމުން ނައްތާލާ", "रूम से हटाएं", "রুম থেকে সরান"),
  room_ban: words("Ban from room", "ރޫމަށް ވަނުން މަނާކުރޭ", "रूम से प्रतिबंधित करें", "রুম থেকে নিষিদ্ধ করুন"),
  room_viewProfile: words("View profile", "ޕްރޮފައިލް ބަލާ", "प्रोफ़ाइल देखें", "প্রোফাইল দেখুন"),
  room_optionsFor: words("Options for {name}", "{name} ގެ އޮޕްޝަންތައް", "{name} के विकल्प", "{name}-এর বিকল্প"),
  room_matchStarting: words("Match starting", "މެޗް ފެށެނީ", "मैच शुरू हो रहा है", "ম্যাচ শুরু হচ্ছে"),
  room_starting: words("Starting…", "ފެށެނީ…", "शुरू हो रहा है…", "শুরু হচ্ছে…"),
  room_needSeats: words("The match can start once all {n} seats are filled.", "{n} ގޮނޑި ފުރުމުން މެޗް ފެށޭނެ.", "सभी {n} सीटें भरने पर मैच शुरू हो सकता है।", "সব {n} আসন পূর্ণ হলে ম্যাচ শুরু হতে পারে।"),
  room_needSeatsShort: words("Needs all {n} seats", "{n} ގޮނޑި ބޭނުން", "सभी {n} सीटें चाहिए", "সব {n} আসন চাই"),
  room_rotateBody: words("Everyone cuts for first play as soon as the table is up. Turn sideways to join them.", "މޭޒު ތައްޔާރުވުމުން ފުރަތަމަ ކުޅޭ މީހާ ހޮވަން ކަޓްކުރާނެ. ފޯނު ހުރަސްކޮށް ވަދޭ.", "मेज़ तैयार होते ही सब पहली बारी के लिए कट करेंगे। जुड़ने के लिए फ़ोन घुमाएं।", "টেবিল প্রস্তুত হলেই সবাই প্রথম পালার জন্য কাট করবে। যোগ দিতে ফোন ঘোরান।"),
  room_allSeated: words("All {n} seated", "{n} މީހުން އިށީންދެފައި", "सभी {n} बैठे", "সব {n} জন বসেছে"),
  room_copyCode: words("Copy code", "ކޯޑް ކޮޕީކުރޭ", "कोड कॉपी करें", "কোড কপি করুন"),
  room_shareLink: words("Share link", "ލިންކް ހިއްސާކުރޭ", "लिंक साझा करें", "লিংক শেয়ার করুন"),
  room_codeCopied: words("Room code copied", "ރޫމް ކޯޑް ކޮޕީވެއްޖެ", "रूम कोड कॉपी हुआ", "রুম কোড কপি হয়েছে"),
  room_linkCopied: words("Invite link copied", "ދަޢުވަތުގެ ލިންކް ކޮޕީވެއްޖެ", "निमंत्रण लिंक कॉपी हुआ", "আমন্ত্রণ লিংক কপি হয়েছে"),
  room_passwordOn: words("Password on", "ޕާސްވޯޑް އޮން", "पासवर्ड चालू", "পাসওয়ার্ড চালু"),
  room_passwordOff: words("Password off", "ޕާސްވޯޑް އޮފް", "पासवर्ड बंद", "পাসওয়ার্ড বন্ধ"),
  room_minutesLeft: words("{n} min left", "{n} މިނެޓް ބާކީ", "{n} मिनट बाकी", "{n} মিনিট বাকি"),
  room_nSeats: words("{n} seats", "{n} ގޮނޑި", "{n} सीटें", "{n} আসন"),
  room_details: words("Room details", "ރޫމުގެ ތަފްޞީލު", "रूम का विवरण", "রুমের বিবরণ"),
  room_privateMode: words("Private room · {game} · {mode}", "ޕްރައިވެޓް ރޫމް · {game} · {mode}", "प्राइवेट रूम · {game} · {mode}", "প্রাইভেট রুম · {game} · {mode}"),
  room_twoTeams: words("two teams", "ދެ ޓީމް", "दो टीमें", "দুই দল"),
  room_oneOnOne: words("one on one", "އެކަކާ އެކަކު", "एक बनाम एक", "এক বনাম এক"),
  room_inviteShort: words("Invite", "ދަޢުވަތުދޭ", "बुलाएं", "আমন্ত্রণ"),
  room_sent: words("Sent", "ފޮނުވިފައި", "भेजा", "পাঠানো"),
  room_joinedShort: words("Joined", "ވަންފައި", "जुड़ गए", "যোগ দিয়েছে"),
  room_inThisRoom: words("In this room", "މި ރޫމުގައި", "इस रूम में", "এই রুমে"),
  room_lastSeen: words("Last seen {n}m ago", "ފަހުން ފެނުނީ {n} މިނެޓް ކުރިން", "{n} मिनट पहले देखा गया", "{n} মিনিট আগে দেখা গেছে"),
  room_invitationSent: words("Invitation sent", "ދަޢުވަތު ފޮނުވިއްޖެ", "निमंत्रण भेजा गया", "আমন্ত্রণ পাঠানো হয়েছে"),
  room_invitationFailed: words("Could not send invitation. Try again.", "ދަޢުވަތު ނުފޮނުވުނު. އަލުން ކުރޭ.", "निमंत्रण नहीं भेजा गया। फिर कोशिश करें।", "আমন্ত্রণ পাঠানো যায়নি। আবার চেষ্টা করুন।"),
  room_searchFriends: words("Search friends", "ރަޙްމަތްތެރިން ހޯދާ", "दोस्त खोजें", "বন্ধু খুঁজুন"),
  room_nOnline: words("{n} online", "{n} އޮންލައިން", "{n} ऑनलाइन", "{n} অনলাইন"),
  room_friendsLoading: words("Loading friends…", "ރަޙްމަތްތެރިން ލޯޑްކުރަނީ…", "दोस्त लोड हो रहे हैं…", "বন্ধু লোড হচ্ছে…"),
  room_friendsError: words("Could not load friends.", "ރަޙްމަތްތެރިން ލޯޑްނުވި.", "दोस्त लोड नहीं हुए।", "বন্ধু লোড করা যায়নি।"),
  room_noFriends: words("No friends yet. Add friends from the Friends page.", "އަދި ރަޙްމަތްތެރިއެއް ނެތް. ރަޙްމަތްތެރިންގެ ޞަފްޙާއިން އިތުރުކުރޭ.", "अभी कोई दोस्त नहीं। दोस्तों के पेज से जोड़ें।", "এখনও বন্ধু নেই। বন্ধু পেজ থেকে যোগ করুন।"),
  room_noMatches: words("No friends match your search.", "ހޯދާ ނަމާ އެއްގޮތް ރަޙްމަތްތެރިއެއް ނެތް.", "आपकी खोज से कोई दोस्त नहीं मिला।", "আপনার খোঁজে কোনো বন্ধু মেলেনি।"),
};
